### ISSUE TITLE
Functions not in namespace

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#22]
Hi,

Several functions are no longer (or never were) exported in the NAMESPACE, so can only be queried and/or debugged from within the FLBEIA function. For example:

> debug(SMFB)
Error in debug(SMFB) : object 'SMFB' not found

But if you debug(FLBEIA) and then debug(SMFB) within the function, it works ok.

This is also true for some functions useful outside of the FLBEIA call, e.g. propagateFLF, which cannot be run - but I see is still in the code on github.

Were these removed (and no longer work) or just deleted accidentally ?

Thanks,
Paul

**Comment by iagomosqueira** [comment]
Just a reminder that unexported functions can still be debugged using `:::`, for example

```
debug(FLBEIA:::SMFB)
```

**Comment by dorleta** [comment]
They have not been deleted. In the new version we don’t export the functions that are used only internally by other functions like SMFB. As Iago said you can always debug or call them outside FLBEIA using “:::”

Dorleta


De: Iago Mosqueira [mailto:notifications@github.com]
Enviado el: lunes, 06 de noviembre de 2017 17:37
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [flr/FLBEIA] Functions not in namespace (#22)


Just a reminder that unexported functions can still be debugged using :::, for example

debug(FLBEIA:::SMFB)

**Comment by pdolder** [comment]
Hi,

Thanks both, good to know about ::: , i hadn't realised this was available.

Should propagateFLF not be available though ?

Paul

**Comment by pdolder** [comment]
Inactive
