### ISSUE TITLE
window on FLFleetExt object fails validityFLMetierExt check

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#29]
Hi,

I am trying to expand my FLFleet object to projection years...but the validity check fails, presumably because it expands the FLCatchesExt before the FLMetiersExt....

You can see with 

```
data(multi)
lapply(multiFl,  window, 1, 5)
```

Error in FUN(X[[i]], ...) : 
  invalid class “FLMetierExt” object: Year range of metier should encompass those of catch(es)

**Comment by pdolder** [comment]
To note that I've used a workaround by redefining window to expand the FLCatchesExt before the FLMetiersExt, as below


```
setMethod("window", signature(x="FLFleetExt"),
 function(x, start=dims(x)$minyear, end=dims(x)$maxyear, extend=TRUE, frequency=1) {

    # window fleet
    x <- qapply(x, window, start, end, extend, frequency)

   # window catches first to avoid the conflict with validFLMetierExt check
    catches <- list()
     metiers <- x@metiers ## move up

    for(i in seq(length(x@metiers))){

      metiers[[i]]@catches <- FLCatchesExt(lapply(x@metiers[[i]]@catches, window, start, end, extend, frequency))


    }

    # window metiers
        metiers <- FLMetiersExt(lapply(metiers, window, start, end))
       
    x@metiers <- metiers

		x@range["minyear"] <- start
		x@range["maxyear"] <- end

		return(x)
	}
)	
```

**Comment by dorleta** [comment]
Hi,

I have rewritten the method and upload it to github.  It works for me, but tell me if there is any problem with it.

Dorleta


De: Paul Dolder <notifications@github.com>
Enviado el: 06 March 2019 17:39
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [flr/FLBEIA] window on FLFleetExt object fails validityFLMetierExt check (#29)


To note that I've used a workaround by redefining window to expand the FLCatchesExt before the FLMetiersExt, as below

setMethod("window", signature(x="FLFleetExt"),

 function(x, start=dims(x)$minyear, end=dims(x)$maxyear, extend=TRUE, frequency=1) {



    # window fleet

    x <- qapply(x, window, start, end, extend, frequency)



   # window catches first to avoid the conflict with validFLMetierExt check

    catches <- list()

     metiers <- x@metiers ## move up



    for(i in seq(length(x@metiers))){



      metiers[[i]]@catches <- FLCatchesExt(lapply(x@metiers[[i]]@catches, window, start, end, extend, frequency))





    }



    # window metiers

        metiers <- FLMetiersExt(lapply(metiers, window, start, end))



    x@metiers <- metiers



               x@range["minyear"] <- start

               x@range["maxyear"] <- end



               return(x)

        }

)

**Comment by pdolder** [comment]
Looks good, works now for me.
