### ISSUE TITLE
advSum providing incorrect response

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#52]
Hi,

I just noticed that the advSum function provides discards in both the landings and the discards slot. It can be traced here:
https://github.com/flr/FLBEIA/blob/3946e1097809b9e795d2b9dc4b2c4309819caeb5/R/Results_Summary.R#L1724

Assume landings should be x3[, 3]

**Comment by ssanchezAZTI** [comment]
Hi Paul,

Thank you for noticing the error!

However, landings are calculated in x2, so the correction should be:
res <- as_tibble(cbind(x1,discards = x3[,4], landings = x2[,4]))

Now is fixed!

Best regards,
Sonia
