### ISSUE TITLE
Error returned when calling 'FLBEIA()' in examples

### ISSUE THREAD

**Issue by marchtaylor** [flr/FLBEIA#9]
First, thank you for creating such detailed documentation of FLBEIA! It should be a model for the rest of FLR.

I am slowly getting into the package and have focused on reproducing the examples found here: http://flbeia.azti.es/how-to-get-started/

I am getting errors from both examples:
1. 1 stock (stk1); 1 fleet (fl1) (1 metier); 1 season
2. 2 stocks (stk1, stk2); 2 fleets (fl1, fl2) (2 metiers); 4 seasons

when trying to call the 'FLBEIA' function (e.g. 1st example - Line 389; 2nd example - Line 483). Below is the output of this error for the 1st example.

I believe my other FLR packages are pretty up-to-date, so I am not sure where this error my be coming from. 

Thanks in advance for your help.

###
```

> s0 <- FLBEIA(biols = biols, SRs = SRs, BDs = BDs, fleets=fleets, covars = covars, 
+               indices = indices, advice = advice, main.ctrl = main.ctrl, 
+               biols.ctrl = biols.ctrl, fleets.ctrl = fleets.ctrl, 
+               covars.ctrl = covars.ctrl, obs.ctrl = obs.ctrl, 
+               assess.ctrl = assess.ctrl, advice.ctrl = advice.ctrl)
############################################################
-                   Year:  21 , Season:  1 
############################################################
************ OPERATING MODEL***************************
------------ BIOLOGICAL OM ------------
-----------------ASPG-----------
------------ FLEETS OM ------------
[1] "~~~~~~~~~~ EFFORT ~~~~~~~~"
[1] "fl1"
[1] "~~~~~~ UPDATE CATCH ~~~~~~"
Warning messages:
1: NAs introduced by coercion 
2: NAs introduced by coercion 
3: NAs introduced by coercion 
4: NAs introduced by coercion 
5: NAs introduced by coercion 
6: NAs introduced by coercion 
7: NAs introduced by coercion 
8: NAs introduced by coercion 
Error in ifelse(Ctotal < tac, 1, tac/Ctotal) : 
  error in evaluating the argument 'no' in selecting a method for function 'ifelse': Error in tac/Ctotal : non-numeric argument to binary operator
```

**Comment by dorleta** [comment]
Hi,

Which R and FLR package versions are you using? At present there are some incompatibilities with the latest versions we are working on fixing it. The examples should work with the packages in: http://flbeia.azti.es/download/ and R.3.0.1.

Best regards,

Dorletat


De: marchtaylor [mailto:notifications@github.com]
Enviado el: jueves, 07 de abril de 2016 14:36
Para: flr/FLBEIA
Asunto: [flr/FLBEIA] Error returned when calling 'FLBEIA()' in examples (#9)


First, thank you for creating such detailed documentation of FLBEIA! It should be a model for the rest of FLR.

I am slowly getting into the package and have focused on reproducing the examples found here: http://flbeia.azti.es/how-to-get-started/

I am getting errors from both examples:
1. 1 stock (stk1); 1 fleet (fl1) (1 metier); 1 season
2. 2 stocks (stk1, stk2); 2 fleets (fl1, fl2) (2 metiers); 4 seasons

when trying to call the 'FLBEIA' function (e.g. 1st example - Line 389; 2nd example - Line 483). Below is the output from this error for the 1st example.

I believe my other FLR packages are pretty up-to-date, so I am not sure where this error my be coming from.

Thanks in advance for your help.

###



> s0 <- FLBEIA(biols = biols, SRs = SRs, BDs = BDs, fleets=fleets, covars = covars,

+               indices = indices, advice = advice, main.ctrl = main.ctrl,

+               biols.ctrl = biols.ctrl, fleets.ctrl = fleets.ctrl,

+               covars.ctrl = covars.ctrl, obs.ctrl = obs.ctrl,

+               assess.ctrl = assess.ctrl, advice.ctrl = advice.ctrl)

############################################################

-                   Year:  21 , Season:  1

############################################################

************ OPERATING MODEL***************************

------------ BIOLOGICAL OM ------------

-----------------ASPG-----------

------------ FLEETS OM ------------

[1] "~~~~~~~~~~ EFFORT ~~~~~~~~"

[1] "fl1"

[1] "~~~~~~ UPDATE CATCH ~~~~~~"

Warning messages:

1: NAs introduced by coercion

2: NAs introduced by coercion

3: NAs introduced by coercion

4: NAs introduced by coercion

5: NAs introduced by coercion

6: NAs introduced by coercion

7: NAs introduced by coercion

8: NAs introduced by coercion

Error in ifelse(Ctotal < tac, 1, tac/Ctotal) :

  error in evaluating the argument 'no' in selecting a method for function 'ifelse': Error in tac/Ctotal : non-numeric argument to binary operator

**Comment by ssanchezAZTI** [comment]
I did tested it using R-3.1.0 and loading the libraries with the following commands:
install.packages(c('plyr', 'ggplot2', 'nloptr', 'mvtnorm', 'triangle'))
install.packages('FLBEIA', repos='http://flr-project.org/R')
And it was working ok!

However, if you still get the error, please contact us again and we will try to find out the problem.

Regards,
FLBEIA team

**Comment by marchtaylor** [comment]
Thanks for your help. This was indeed a problem with my R version - I was using R 3.2.3 (32-Bit). With R 3.1.0 everything works fine. 

Cheers,
Marc

**Comment by iagomosqueira** [comment]
We will be able to prepare FLBEIA for R 3.2 very soo n, or maybe jump to 
3.3 when it comes out

**Comment by marchtaylor** [comment]
Excellent - Thank you very much
